In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51)
             )
scores_pd

     國文  英文  數學   地理  歷史
1    63  51  54   80  94
2    53  72  75   93  64
3    69  52  92   89  95
4    73  78  88   80  84
5    53  71  88   65  61
6    95  74  84  100  83
7    89  88  80   93  67
8    58  97  90   79  84
9    53  79  90   53  94
10  100  50  65   99  85
11   89  98  67   50  94
12   51  53  96   53  90
13   89  87  79   59  50
14   65  73  54   64  98
15   56  72  97   66  67
16   57  88  61   78  83
17   96  96  93   53  77
18   80  76  54   85  79
19   74  53  52   50  66
20   56  69  82   54  98
21   69  98  69   89  98
22   78  65  82   84  94
23   69  73  90   99  63
24   75  55  56   89  74
25   69  63  90   96  98
26   60  53  78   66  88
27   88  93  82   97  72
28   97  90  66   84  53
29   84  87  56   96  95
30   92  70  85   77  84
31   53  91  62   81  62
32   59  81  79   87  54
33   71  96  54   56  72
34   53  83  96   68  83
35   53  63  58   59  59
36   80  55  90   92  70
37   68  96  51   63  52
38   66  69  91   78  67
39   63  90  67   51  75
40   92  98  67   81  51
41   94  90  68   75  89
42   75  54  86   92  65
43   89  52  75   58  70
44   84  71  62   59  99
45   52  96  89   60  65
46   54  80  50   89  74
47   68  86  65   87  99
48   87  86  80   61  94
49   85  50  69   86  54
50  100  82  74   53  66

In [2]:
def callback1(value:pd.Series):
    return pd.Series([value.max(),value.min(),value.median(),value.mean()],index=['最高分','最低分','中間值','平均值'])
    
dataFrame1 = scores_pd.apply(callback1)
dataFrame1

         國文     英文     數學      地理     歷史
最高分  100.00  98.00  97.00  100.00  99.00
最低分   51.00  50.00  50.00   50.00  50.00
中間值   70.00  77.00  76.50   78.50  76.00
平均值   72.92  75.86  74.56   75.12  77.04