In [11]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index = range(1,51)
             )
scores_pd

     國文   英文   數學   地理  歷史
1    65   53   52   63  64
2    73   95   58   62  83
3    50   71   95   50  98
4    95   98   83   59  90
5    54   68   98   52  85
6    53   97   52   60  60
7    87   53   58   62  55
8    82   73  100   74  82
9    69   95   79   81  68
10   62   56   61   78  59
11   81   68   65   68  53
12   84   92   57   60  98
13   56   70   74   73  72
14   64   90   87   85  62
15   83   93   75   87  93
16   82   73   92   90  92
17   77   95   91   85  82
18   61   77   57   84  92
19   60   75   87   70  94
20   72   99   65   77  93
21   81   63   61   64  71
22   83   77   51  100  60
23   72   54   51   59  55
24   57   68   60   58  57
25   89   81   59   59  70
26   65   62   56   58  86
27   61   58   63   53  95
28   93   82   62   98  75
29   85   60   77   88  63
30   55   60   68   93  68
31   99   84   84   73  65
32   53   96   73   76  66
33   71   61   76   84  78
34   59   95   92   89  53
35   76   83   78   88  58
36   50  100   62   83  75
37   67   97   81   69  68
38   86   72   81   87  69
39   66   90   93   98  53
40   76   79   78   77  57
41   70   87   87   65  71
42  100   79   81   64  72
43   96   78   53   59  99
44   84   61   76   61  95
45   84   89   91   50  68
46   88   75   57   56  97
47   57   92   71   57  86
48   77   79   95   72  81
49   96   75   58   57  86
50   84   71   64   74  91

In [12]:
scores_pd.index.name="學號"
scores_pd.columns.name="科目"
scores_pd

科目   國文   英文   數學   地理  歷史
學號
1    65   53   52   63  64
2    73   95   58   62  83
3    50   71   95   50  98
4    95   98   83   59  90
5    54   68   98   52  85
6    53   97   52   60  60
7    87   53   58   62  55
8    82   73  100   74  82
9    69   95   79   81  68
10   62   56   61   78  59
11   81   68   65   68  53
12   84   92   57   60  98
13   56   70   74   73  72
14   64   90   87   85  62
15   83   93   75   87  93
16   82   73   92   90  92
17   77   95   91   85  82
18   61   77   57   84  92
19   60   75   87   70  94
20   72   99   65   77  93
21   81   63   61   64  71
22   83   77   51  100  60
23   72   54   51   59  55
24   57   68   60   58  57
25   89   81   59   59  70
26   65   62   56   58  86
27   61   58   63   53  95
28   93   82   62   98  75
29   85   60   77   88  63
30   55   60   68   93  68
31   99   84   84   73  65
32   53   96   73   76  66
33   71   61   76   84  78
34   59   95   92   89  53
35   76   83   78   88  58
36   50  100   62   83  75
37   67   97   81   69  68
38   86   72   81   87  69
39   66   90   93   98  53
40   76   79   78   77  57
41   70   87   87   65  71
42  100   79   81   64  72
43   96   78   53   59  99
44   84   61   76   61  95
45   84   89   91   50  68
46   88   75   57   56  97
47   57   92   71   57  86
48   77   79   95   72  81
49   96   75   58   57  86
50   84   71   64   74  91

In [13]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]
scores_pd.info()

學號
1     65
2     73
3     50
4     95
5     54
6     53
7     87
8     82
9     69
10    62
Name: 國文, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int64
 1   英文      50 non-null     int64
 2   數學      50 non-null     int64
 3   地理      50 non-null     int64
 4   歷史      50 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

In [14]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     117
2     131
3     145
4     178
5     152
6     105
7     145
8     182
9     148
10    123
dtype: int64

In [15]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     297
2     371
3     364
4     425
5     357
6     322
7     315
8     411
9     392
10    316
11    335
12    391
13    345
14    388
15    431
16    429
17    430
18    371
19    386
20    406
21    340
22    371
23    291
24    300
25    358
26    327
27    330
28    410
29    373
30    344
31    405
32    364
33    370
34    388
35    383
36    370
37    382
38    395
39    400
40    367
41    380
42    396
43    385
44    377
45    382
46    373
47    363
48    404
49    372
50    384
dtype: int64

In [16]:
#統計的實體方法,sum()
scores_pd['總分'] = scores_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_pd
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1)
scores_pd

科目   國文   英文   數學   地理  歷史   總分    平均
學號
1    65   53   52   63  64  297  59.4
2    73   95   58   62  83  371  74.2
3    50   71   95   50  98  364  72.8
4    95   98   83   59  90  425  85.0
5    54   68   98   52  85  357  71.4
6    53   97   52   60  60  322  64.4
7    87   53   58   62  55  315  63.0
8    82   73  100   74  82  411  82.2
9    69   95   79   81  68  392  78.4
10   62   56   61   78  59  316  63.2
11   81   68   65   68  53  335  67.0
12   84   92   57   60  98  391  78.2
13   56   70   74   73  72  345  69.0
14   64   90   87   85  62  388  77.6
15   83   93   75   87  93  431  86.2
16   82   73   92   90  92  429  85.8
17   77   95   91   85  82  430  86.0
18   61   77   57   84  92  371  74.2
19   60   75   87   70  94  386  77.2
20   72   99   65   77  93  406  81.2
21   81   63   61   64  71  340  68.0
22   83   77   51  100  60  371  74.2
23   72   54   51   59  55  291  58.2
24   57   68   60   58  57  300  60.0
25   89   81   59   59  70  358  71.6
26   65   62   56   58  86  327  65.4
27   61   58   63   53  95  330  66.0
28   93   82   62   98  75  410  82.0
29   85   60   77   88  63  373  74.6
30   55   60   68   93  68  344  68.8
31   99   84   84   73  65  405  81.0
32   53   96   73   76  66  364  72.8
33   71   61   76   84  78  370  74.0
34   59   95   92   89  53  388  77.6
35   76   83   78   88  58  383  76.6
36   50  100   62   83  75  370  74.0
37   67   97   81   69  68  382  76.4
38   86   72   81   87  69  395  79.0
39   66   90   93   98  53  400  80.0
40   76   79   78   77  57  367  73.4
41   70   87   87   65  71  380  76.0
42  100   79   81   64  72  396  79.2
43   96   78   53   59  99  385  77.0
44   84   61   76   61  95  377  75.4
45   84   89   91   50  68  382  76.4
46   88   75   57   56  97  373  74.6
47   57   92   71   57  86  363  72.6
48   77   79   95   72  81  404  80.8
49   96   75   58   57  86  372  74.4
50   84   71   64   74  91  384  76.8

In [17]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min',ascending=False)
scores_pd

科目   國文   英文   數學   地理  歷史   總分    平均    排名
學號
1    65   53   52   63  64  297  59.4  49.0
2    73   95   58   62  83  371  74.2  28.0
3    50   71   95   50  98  364  72.8  34.0
4    95   98   83   59  90  425  85.0   4.0
5    54   68   98   52  85  357  71.4  38.0
6    53   97   52   60  60  322  64.4  45.0
7    87   53   58   62  55  315  63.0  47.0
8    82   73  100   74  82  411  82.2   5.0
9    69   95   79   81  68  392  78.4  13.0
10   62   56   61   78  59  316  63.2  46.0
11   81   68   65   68  53  335  67.0  42.0
12   84   92   57   60  98  391  78.2  14.0
13   56   70   74   73  72  345  69.0  39.0
14   64   90   87   85  62  388  77.6  15.0
15   83   93   75   87  93  431  86.2   1.0
16   82   73   92   90  92  429  85.8   3.0
17   77   95   91   85  82  430  86.0   2.0
18   61   77   57   84  92  371  74.2  28.0
19   60   75   87   70  94  386  77.2  17.0
20   72   99   65   77  93  406  81.2   7.0
21   81   63   61   64  71  340  68.0  41.0
22   83   77   51  100  60  371  74.2  28.0
23   72   54   51   59  55  291  58.2  50.0
24   57   68   60   58  57  300  60.0  48.0
25   89   81   59   59  70  358  71.6  37.0
26   65   62   56   58  86  327  65.4  44.0
27   61   58   63   53  95  330  66.0  43.0
28   93   82   62   98  75  410  82.0   6.0
29   85   60   77   88  63  373  74.6  25.0
30   55   60   68   93  68  344  68.8  40.0
31   99   84   84   73  65  405  81.0   8.0
32   53   96   73   76  66  364  72.8  34.0
33   71   61   76   84  78  370  74.0  31.0
34   59   95   92   89  53  388  77.6  15.0
35   76   83   78   88  58  383  76.6  20.0
36   50  100   62   83  75  370  74.0  31.0
37   67   97   81   69  68  382  76.4  21.0
38   86   72   81   87  69  395  79.0  12.0
39   66   90   93   98  53  400  80.0  10.0
40   76   79   78   77  57  367  73.4  33.0
41   70   87   87   65  71  380  76.0  23.0
42  100   79   81   64  72  396  79.2  11.0
43   96   78   53   59  99  385  77.0  18.0
44   84   61   76   61  95  377  75.4  24.0
45   84   89   91   50  68  382  76.4  21.0
46   88   75   57   56  97  373  74.6  25.0
47   57   92   71   57  86  363  72.6  36.0
48   77   79   95   72  81  404  80.8   9.0
49   96   75   58   57  86  372  74.4  27.0
50   84   71   64   74  91  384  76.8  19.0

In [18]:
scores_pd.sort_values(by='排名')

科目   國文   英文   數學   地理  歷史   總分    平均    排名
學號
15   83   93   75   87  93  431  86.2   1.0
17   77   95   91   85  82  430  86.0   2.0
16   82   73   92   90  92  429  85.8   3.0
4    95   98   83   59  90  425  85.0   4.0
8    82   73  100   74  82  411  82.2   5.0
28   93   82   62   98  75  410  82.0   6.0
20   72   99   65   77  93  406  81.2   7.0
31   99   84   84   73  65  405  81.0   8.0
48   77   79   95   72  81  404  80.8   9.0
39   66   90   93   98  53  400  80.0  10.0
42  100   79   81   64  72  396  79.2  11.0
38   86   72   81   87  69  395  79.0  12.0
9    69   95   79   81  68  392  78.4  13.0
12   84   92   57   60  98  391  78.2  14.0
14   64   90   87   85  62  388  77.6  15.0
34   59   95   92   89  53  388  77.6  15.0
19   60   75   87   70  94  386  77.2  17.0
43   96   78   53   59  99  385  77.0  18.0
50   84   71   64   74  91  384  76.8  19.0
35   76   83   78   88  58  383  76.6  20.0
45   84   89   91   50  68  382  76.4  21.0
37   67   97   81   69  68  382  76.4  21.0
41   70   87   87   65  71  380  76.0  23.0
44   84   61   76   61  95  377  75.4  24.0
46   88   75   57   56  97  373  74.6  25.0
29   85   60   77   88  63  373  74.6  25.0
49   96   75   58   57  86  372  74.4  27.0
18   61   77   57   84  92  371  74.2  28.0
22   83   77   51  100  60  371  74.2  28.0
2    73   95   58   62  83  371  74.2  28.0
33   71   61   76   84  78  370  74.0  31.0
36   50  100   62   83  75  370  74.0  31.0
40   76   79   78   77  57  367  73.4  33.0
3    50   71   95   50  98  364  72.8  34.0
32   53   96   73   76  66  364  72.8  34.0
47   57   92   71   57  86  363  72.6  36.0
25   89   81   59   59  70  358  71.6  37.0
5    54   68   98   52  85  357  71.4  38.0
13   56   70   74   73  72  345  69.0  39.0
30   55   60   68   93  68  344  68.8  40.0
21   81   63   61   64  71  340  68.0  41.0
11   81   68   65   68  53  335  67.0  42.0
27   61   58   63   53  95  330  66.0  43.0
26   65   62   56   58  86  327  65.4  44.0
6    53   97   52   60  60  322  64.4  45.0
10   62   56   61   78  59  316  63.2  46.0
7    87   53   58   62  55  315  63.0  47.0
24   57   68   60   58  57  300  60.0  48.0
1    65   53   52   63  64  297  59.4  49.0
23   72   54   51   59  55  291  58.2  50.0

In [19]:
def format60(v:int):
    if v >= 60:
        return '及格'
    else:
        return '不及格'

scores_pd[['國文','英文','數學','地理','歷史']].style.format(format60)

In [20]:
scores_pd.style\
.highlight_between(left=0,
                   right=59,
                   color='red',
                   subset=['國文','英文','數學','地理','歷史'],
                   props='color:white;background-color:red')\
.format(precision=0,subset=['平均','排名']).to_excel('scores.xlsx')